apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  labels:
    app: microservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: justmorpheu5/microservice2:latest
        ports:
        - containerPort: 5001
        env:
        - name: SECRET_KEY
          value: secret
