---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"
    - name: fetch admin.conf from master
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/config
        flat: yes

- hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - name: remove swap
      shell: "swapoff -a"
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
    - name: create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
    - name: copy admin.conf from fetched location to worker
      copy:
        src: /tmp/config
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
    - name: set permission of kube config
      shell: "sudo chown ubuntu:ubuntu -R /home/ubuntu/.kube"
