apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  labels:
    app: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: justmorpheu5/microservice1:latest
        ports:
        - containerPort: 8080
        env:
        - name: SECRET_KEY
          value: secret
