apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-legacy
  namespace: legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      serviceAccountName: secret-sa
      containers:
      - name: hello-world
        image: alpine
        command: "hello world"
